// Demo courses (c001–c009) — the real Formation Exceptionelle catalog, transcribed
// from the live frontend (corporate / legal / finance programmes). Matches §5.2 / §16.
// `lectureCount` is the marketing figure shown on the cards; the sample curriculum is
// smaller (the frontend reads the field, not the array length). All seeded courses
// are `published`. Prices are NGN (₦18,000–₦40,000; strike-through ₦28,000–₦58,000).
const SAMPLE = 'https://storage.googleapis.com/gtv-videos-bucket/sample';

const v = (name) => `${SAMPLE}/${name}.mp4`;
const lec = (id, title, duration, { type = 'video', preview = false, vid } = {}) => ({
  id,
  title,
  duration,
  type,
  preview,
  videoUrl: type === 'video' && vid ? v(vid) : '',
  videoAsset: null,
});

// A light, representative 2-section curriculum (matches the mock's sample lessons).
function sampleCurriculum(l1Title, l2Title, l3Title, l4Title, vids) {
  return [
    {
      id: 's1',
      title: 'Foundations',
      duration: '6h 10m',
      lectures: [
        lec('l1', l1Title, '18:30', { preview: true, vid: vids[0] }),
        lec('l2', l2Title, '30:45', { vid: vids[1] }),
        lec('l3', 'Module Assessment', '10 questions', { type: 'quiz' }),
      ],
    },
    {
      id: 's2',
      title: 'Advanced Practice',
      duration: '5h 30m',
      lectures: [
        lec('l4', l3Title, '24:10', { vid: vids[2] }),
        lec('l5', l4Title, '21:05', { vid: vids[3] }),
      ],
    },
  ];
}

export const DEMO_COURSES = [
  {
    _id: 'c001',
    title:
      'Financing, Mergers & Acquisitions and Alternative Dispute Resolution (ADR): Advanced Practice, Procedure & Negotiation',
    subtitle:
      'Advanced practice across deal financing, mergers & acquisitions and alternative dispute resolution',
    description:
      'A flagship programme covering deal financing structures, M&A execution, and negotiation and ADR strategy for complex corporate transactions. Designed for practitioners who advise on high-value deals and the disputes that can arise from them.',
    instructor: { id: 'inst-okafor', name: 'Barr. (Mrs.) Adaeze Okafor, SAN', avatar: null, rating: 4.9, students: 4200 },
    instructorId: 'inst-okafor',
    category: 'Dispute Resolution',
    subcategory: 'Corporate Transactions',
    level: 'Advanced',
    language: 'English',
    price: 35000,
    originalPrice: 52000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
    previewVideo: v('BigBuckBunny'),
    rating: 4.9,
    reviewCount: 612,
    enrolledCount: 4200,
    duration: '24 hours',
    lectureCount: 48,
    lastUpdated: '2026-01-15',
    certificate: true,
    tags: ['m&a', 'financing', 'adr', 'negotiation', 'dispute resolution'],
    requirements: ['A legal or finance background is recommended', 'Some transactional experience helps'],
    objectives: [
      'Structure and negotiate deal financing',
      'Execute mergers and acquisitions end to end',
      'Resolve disputes through arbitration and mediation',
      'Lead high-stakes commercial negotiations',
    ],
    featured: true,
    status: 'published',
    sections: sampleCurriculum(
      'Deal Financing Structures',
      'M&A Process & Documentation',
      'Negotiation Strategy',
      'Arbitration & Mediation in Practice',
      ['BigBuckBunny', 'ElephantsDream', 'ForBiggerBlazes', 'ForBiggerEscapes']
    ),
  },
  {
    _id: 'c002',
    title: 'Company Secretarial Practice',
    subtitle: 'Master the compliance, filings and board-support function',
    description:
      'Master statutory compliance, board administration, statutory registers and corporate filings for the modern company secretary. Built around real board cycles and regulatory obligations.',
    instructor: { id: 'inst-bakare', name: 'Mr. Tunde Bakare, FCIS', avatar: null, rating: 4.8, students: 2860 },
    instructorId: 'inst-bakare',
    category: 'Corporate Governance',
    subcategory: 'Company Secretarial',
    level: 'Intermediate',
    language: 'English',
    price: 18000,
    originalPrice: 28000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800',
    previewVideo: v('ForBiggerFun'),
    rating: 4.8,
    reviewCount: 418,
    enrolledCount: 2860,
    duration: '16 hours',
    lectureCount: 34,
    lastUpdated: '2026-02-02',
    certificate: true,
    tags: ['company secretary', 'compliance', 'governance', 'filings'],
    requirements: ['An interest in corporate administration and compliance'],
    objectives: [
      'Administer board and committee meetings',
      'Maintain statutory registers and filings',
      'Advise on governance and compliance obligations',
    ],
    featured: true,
    status: 'published',
    sections: sampleCurriculum(
      'The Company Secretary Role',
      'Statutory Registers & Filings',
      'Board & Committee Administration',
      'Shareholder & Regulatory Relations',
      ['ForBiggerFun', 'ForBiggerJoyrides', 'ForBiggerMeltdowns', 'ElephantsDream']
    ),
  },
  {
    _id: 'c003',
    title:
      'Strategic Leadership & Corporate Governance: Aligning Strategy, Ethics, Performance & Stakeholder Management for High-Impact',
    subtitle:
      'Lead at board level by aligning strategy, ethics, performance and stakeholder interests',
    description:
      'Designed for directors, senior executives and aspiring board members, this programme connects strategic leadership with sound corporate governance. It explores board effectiveness, ethical decision-making, performance oversight, risk and stakeholder management — equipping leaders to drive high-impact, accountable organisations.',
    instructor: { id: 'inst-eze', name: 'Dr. Ngozi Eze', avatar: null, rating: 4.9, students: 3540 },
    instructorId: 'inst-eze',
    category: 'Corporate Governance',
    subcategory: 'Leadership & Strategy',
    level: 'Advanced',
    language: 'English',
    price: 28000,
    originalPrice: 45000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800',
    previewVideo: v('TearsOfSteel'),
    rating: 4.9,
    reviewCount: 503,
    enrolledCount: 3540,
    duration: '20 hours',
    lectureCount: 40,
    lastUpdated: '2026-05-30',
    certificate: true,
    tags: ['leadership', 'governance', 'board', 'strategy', 'ethics'],
    requirements: ['Management or board-level experience helpful', 'Interest in governance and strategy'],
    objectives: [
      'Align corporate strategy with governance and ethics',
      'Strengthen board effectiveness and accountability',
      'Oversee performance, risk and internal controls',
      'Manage stakeholders for sustainable, high-impact outcomes',
    ],
    featured: true,
    status: 'published',
    sections: [
      {
        id: 's1',
        title: 'Foundations of Strategic Governance',
        duration: '6h 10m',
        lectures: [
          lec('l1', 'What Makes a High-Impact Board?', '18:30', { preview: true, vid: 'TearsOfSteel' }),
          lec('l2', 'Strategy, Ethics & Corporate Purpose', '30:45', { vid: 'SubaruOutbackOnStreetAndDirt' }),
        ],
      },
      {
        id: 's2',
        title: 'Performance & Stakeholder Management',
        duration: '5h 30m',
        lectures: [
          lec('l3', 'Performance Oversight, Risk & Internal Controls', '27:20', { vid: 'ForBiggerBlazes' }),
          lec('l4', 'Stakeholder Management for High-Impact Outcomes', '25:50', { vid: 'ForBiggerEscapes' }),
        ],
      },
    ],
  },
  {
    _id: 'c004',
    title: 'Navigating Law & Digital Innovation: AI, Fintech & Data Protection',
    subtitle: 'The legal frontier of technology, finance and privacy',
    description:
      'Understand the legal and regulatory issues at the intersection of artificial intelligence, fintech and data protection. A practical guide for lawyers and compliance professionals advising technology-driven businesses.',
    instructor: { id: 'inst-obi', name: 'Prof. Emeka Obi', avatar: null, rating: 4.7, students: 2100 },
    instructorId: 'inst-obi',
    category: 'Corporate Law',
    subcategory: 'Technology Law',
    level: 'Intermediate',
    language: 'English',
    price: 25000,
    originalPrice: 42000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    previewVideo: v('VolkswagenGTIReview'),
    rating: 4.7,
    reviewCount: 357,
    enrolledCount: 2100,
    duration: '18 hours',
    lectureCount: 36,
    lastUpdated: '2026-03-12',
    certificate: true,
    tags: ['ai', 'fintech', 'data protection', 'technology law', 'privacy'],
    requirements: ['Foundational legal knowledge is helpful'],
    objectives: [
      'Advise on AI and emerging-technology regulation',
      'Navigate fintech licensing and compliance',
      'Apply data-protection and privacy frameworks',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'AI, Law & Regulation',
      'Fintech Licensing & Compliance',
      'Data Protection & Privacy',
      'Cross-Border Data & Emerging Risk',
      ['VolkswagenGTIReview', 'WeAreGoingOnBullrun', 'WhatCarCanYouGetForAGrand', 'ForBiggerJoyrides']
    ),
  },
  {
    _id: 'c005',
    title: 'Capital Market: Corporate Financing, Regulations & Compliance',
    subtitle: 'Raise capital within the regulatory perimeter',
    description:
      'A deep dive into capital-market instruments, issuance, regulatory approvals and ongoing compliance obligations. Ideal for finance professionals and lawyers supporting capital raises.',
    instructor: { id: 'inst-nwankwo', name: 'Mr. Chukwuma Nwankwo, FCA', avatar: null, rating: 4.8, students: 3120 },
    instructorId: 'inst-nwankwo',
    category: 'Finance & Capital Markets',
    subcategory: 'Capital Markets',
    level: 'Intermediate',
    language: 'English',
    price: 30000,
    originalPrice: 48000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
    previewVideo: v('ForBiggerBlazes'),
    rating: 4.8,
    reviewCount: 446,
    enrolledCount: 3120,
    duration: '19 hours',
    lectureCount: 38,
    lastUpdated: '2026-02-20',
    certificate: true,
    tags: ['capital markets', 'securities', 'compliance', 'financing'],
    requirements: ['Basic understanding of finance or corporate law'],
    objectives: [
      'Structure capital-market instruments and issuances',
      'Secure regulatory approvals for capital raises',
      'Maintain ongoing market-compliance obligations',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'Capital-Market Instruments',
      'Issuance & Regulatory Approvals',
      'Disclosure & Ongoing Compliance',
      'Enforcement & Market Conduct',
      ['ForBiggerBlazes', 'BigBuckBunny', 'ElephantsDream', 'ForBiggerFun']
    ),
  },
  {
    _id: 'c006',
    title: 'Project Structuring & Financing, Advanced Fiscal Modelling & ESG Integration',
    subtitle: 'Bankable, sustainable project finance',
    description:
      'Structure and finance large projects while integrating environmental, social and governance (ESG) considerations and advanced fiscal modelling. Built for energy, infrastructure and development finance professionals.',
    instructor: { id: 'inst-bello', name: 'Engr. Yusuf Bello', avatar: null, rating: 4.8, students: 1900 },
    instructorId: 'inst-bello',
    category: 'Energy & ESG',
    subcategory: 'Project Finance',
    level: 'Advanced',
    language: 'English',
    price: 40000,
    originalPrice: 58000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800',
    previewVideo: v('ForBiggerMeltdowns'),
    rating: 4.8,
    reviewCount: 288,
    enrolledCount: 1900,
    duration: '22 hours',
    lectureCount: 44,
    lastUpdated: '2026-03-28',
    certificate: true,
    tags: ['project finance', 'esg', 'energy', 'infrastructure', 'fiscal modelling'],
    requirements: ['Comfort with financial concepts and spreadsheets'],
    objectives: [
      'Structure bankable project-finance transactions',
      'Build advanced fiscal models',
      'Integrate ESG into project design and financing',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'Project Structuring Fundamentals',
      'Advanced Fiscal Modelling',
      'ESG Integration',
      'Risk Allocation & Closing',
      ['ForBiggerMeltdowns', 'SubaruOutbackOnStreetAndDirt', 'TearsOfSteel', 'VolkswagenGTIReview']
    ),
  },
  {
    _id: 'c007',
    title: 'Mergers and Acquisitions: Regulations, Risks Management & Strategic Execution',
    subtitle: 'Execute M&A within the rules, manage the risk',
    description:
      'From due diligence to closing — the regulatory regime, antitrust clearance and risk allocation in M&A deals. A rigorous, execution-focused programme for transaction professionals.',
    instructor: { id: 'inst-abdullahi', name: 'Mrs. Fatima Abdullahi', avatar: null, rating: 4.7, students: 2200 },
    instructorId: 'inst-abdullahi',
    category: 'Mergers & Acquisitions',
    subcategory: 'Transactions',
    level: 'Advanced',
    language: 'English',
    price: 32000,
    originalPrice: 50000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    previewVideo: v('WeAreGoingOnBullrun'),
    rating: 4.7,
    reviewCount: 321,
    enrolledCount: 2200,
    duration: '21 hours',
    lectureCount: 42,
    lastUpdated: '2026-03-05',
    certificate: true,
    tags: ['m&a', 'antitrust', 'due diligence', 'risk'],
    requirements: ['Transactional or advisory experience recommended'],
    objectives: [
      'Run regulatory and antitrust analysis for deals',
      'Manage and allocate transaction risk',
      'Execute M&A from diligence to closing',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'M&A Regulatory Landscape',
      'Antitrust & Merger Control',
      'Risk Management & Allocation',
      'Execution & Closing',
      ['WeAreGoingOnBullrun', 'WhatCarCanYouGetForAGrand', 'ForBiggerEscapes', 'ForBiggerJoyrides']
    ),
  },
  {
    _id: 'c008',
    title:
      'Due Diligence and Contractual Risk Management in Agreements and Cross-Border Transactions, Agreements & Investments',
    subtitle: 'Find the risk before it finds you',
    description:
      'Conduct rigorous legal due diligence and draft contracts that allocate and mitigate commercial risk across domestic and cross-border transactions, agreements and investments.',
    instructor: { id: 'inst-anyim', name: 'Barr. Kelechi Anyim', avatar: null, rating: 4.7, students: 2050 },
    instructorId: 'inst-anyim',
    category: 'Corporate Law',
    subcategory: 'Contracts & Risk',
    level: 'Intermediate',
    language: 'English',
    price: 24000,
    originalPrice: 38000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    previewVideo: v('WhatCarCanYouGetForAGrand'),
    rating: 4.7,
    reviewCount: 264,
    enrolledCount: 2050,
    duration: '17 hours',
    lectureCount: 34,
    lastUpdated: '2026-02-26',
    certificate: true,
    tags: ['due diligence', 'contracts', 'risk management', 'cross-border'],
    requirements: ['Foundational contract-law knowledge'],
    objectives: [
      'Conduct thorough legal due diligence',
      'Draft contracts that allocate and mitigate risk',
      'Manage cross-border transaction risk',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'Legal Due Diligence',
      'Contractual Risk Allocation',
      'Cross-Border Considerations',
      'Drafting & Negotiation Clinics',
      ['WhatCarCanYouGetForAGrand', 'ForBiggerFun', 'ForBiggerBlazes', 'BigBuckBunny']
    ),
  },
  {
    _id: 'c009',
    title: 'The New Tax Laws: Hindsight, Foresight & Strategic Implications',
    subtitle: 'Stay compliant and ahead under the latest tax regime',
    description:
      'A practical guide to recent tax legislation, compliance obligations and planning opportunities for businesses and advisors — demystifying the reforms and their strategic implications.',
    instructor: { id: 'inst-adeyinka', name: 'Mr. Gbenga Adeyinka, FCTI', avatar: null, rating: 4.8, students: 2980 },
    instructorId: 'inst-adeyinka',
    category: 'Taxation',
    subcategory: 'Tax Law & Policy',
    level: 'All Levels',
    language: 'English',
    price: 22000,
    originalPrice: 36000,
    currency: 'NGN',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    previewVideo: v('ForBiggerJoyrides'),
    rating: 4.8,
    reviewCount: 401,
    enrolledCount: 2980,
    duration: '15 hours',
    lectureCount: 30,
    lastUpdated: '2026-04-10',
    certificate: true,
    tags: ['tax', 'compliance', 'regulation', 'planning'],
    requirements: ['No prior tax knowledge required'],
    objectives: [
      'Understand the latest tax legislation',
      'Meet new compliance obligations',
      'Advise on strategic tax-planning opportunities',
    ],
    featured: false,
    status: 'published',
    sections: sampleCurriculum(
      'The Reforms in Context',
      'Compliance Under the New Regime',
      'Strategic Tax Planning',
      'Sector Case Studies',
      ['ForBiggerJoyrides', 'ElephantsDream', 'TearsOfSteel', 'SubaruOutbackOnStreetAndDirt']
    ),
  },
];
