// Demo jobs (j001–j005) — the real Formation Exceptionelle board, transcribed from
// the live frontend. `postedBy` is filled in by the seed script. Seeded jobs are
// approved + active. Salaries are NGN/month.
export const DEMO_JOBS = [
  {
    _id: 'j001',
    title: 'Corporate / Commercial Lawyer',
    company: 'Adebayo & Okonkwo LP',
    companyLogo: null,
    location: 'Lagos, Nigeria',
    locationType: 'On-site',
    type: 'Full-time',
    category: 'Legal',
    salary: { min: 450000, max: 750000, currency: 'NGN', period: 'monthly' },
    experience: '3-5 years',
    level: 'Senior',
    description:
      'Adebayo & Okonkwo LP is seeking a corporate/commercial lawyer to advise on transactions, contracts, M&A and regulatory matters for a diverse client portfolio.',
    responsibilities: [
      'Draft and negotiate commercial agreements',
      'Advise on corporate transactions and compliance',
      'Support M&A due diligence and execution',
      'Manage client relationships and matters',
    ],
    requirements: ['LLB and call to the Nigerian Bar', '3+ years in corporate/commercial practice', 'Strong drafting and negotiation skills'],
    benefits: ['Health insurance', 'Performance bonus', 'Professional development'],
    skills: ['Corporate Law', 'Contract Drafting', 'Due Diligence', 'Negotiation', 'Corporate Governance'],
    deadline: '2026-07-31',
    postedAt: '2026-06-12',
    applications: 47,
    isActive: true,
    isFeatured: true,
    status: 'approved',
  },
  {
    _id: 'j002',
    title: 'Legal & Compliance Intern',
    company: 'Meridian Capital Partners',
    companyLogo: null,
    location: 'Abuja, Nigeria',
    locationType: 'Hybrid',
    type: 'Internship',
    category: 'Compliance & Risk',
    salary: { min: 120000, max: 180000, currency: 'NGN', period: 'monthly' },
    experience: '0-1 year',
    level: 'Entry',
    description:
      'Support the legal and compliance team on regulatory research, policy reviews and risk assessments at a growing investment firm.',
    responsibilities: ['Conduct regulatory research', 'Assist with compliance monitoring', 'Maintain policy documentation'],
    requirements: ['Law or related degree (in view or completed)', 'Strong research and writing skills'],
    benefits: ['Mentorship', 'Certificate of completion', 'Potential full-time offer'],
    skills: ['Compliance', 'Legal Research', 'Risk', 'Regulatory Affairs', 'Documentation'],
    deadline: '2026-07-15',
    postedAt: '2026-06-10',
    applications: 128,
    isActive: true,
    isFeatured: true,
    status: 'approved',
  },
  {
    _id: 'j003',
    title: 'Company Secretary / Governance Officer',
    company: 'Sterling Holdings Plc',
    companyLogo: null,
    location: 'Lagos, Nigeria',
    locationType: 'On-site',
    type: 'Full-time',
    category: 'Corporate Governance',
    salary: { min: 400000, max: 650000, currency: 'NGN', period: 'monthly' },
    experience: '5-10 years',
    level: 'Manager',
    description:
      'Lead the company secretarial and governance function: board support, statutory compliance and shareholder relations.',
    responsibilities: ['Administer board and committee meetings', 'Maintain statutory registers and filings', 'Advise on governance best practice'],
    requirements: ['ICSAN qualification or equivalent', '5+ years in a secretarial/governance role'],
    benefits: ['Health insurance', 'Pension', 'Career growth'],
    skills: ['Company Secretarial', 'Corporate Governance', 'Compliance', 'Board Administration', 'Statutory Filings'],
    deadline: '2026-07-20',
    postedAt: '2026-06-08',
    applications: 83,
    isActive: true,
    isFeatured: false,
    status: 'approved',
  },
  {
    _id: 'j004',
    title: 'Tax Manager',
    company: 'Harcourt Advisory',
    companyLogo: null,
    location: 'Lagos, Nigeria',
    locationType: 'Hybrid',
    type: 'Full-time',
    category: 'Tax',
    salary: { min: 500000, max: 850000, currency: 'NGN', period: 'monthly' },
    experience: '5-8 years',
    level: 'Manager',
    description:
      'Harcourt Advisory is hiring a Tax Manager to lead tax advisory and compliance engagements, advise clients on the new tax laws and develop tax-efficient strategies.',
    responsibilities: [
      'Lead tax compliance and advisory engagements',
      'Advise clients on the implications of new tax laws',
      'Develop tax-efficient structures and strategies',
      'Manage relationships with tax authorities',
      'Review filings and supervise junior associates',
    ],
    requirements: [
      'ACA/ACCA/CITN qualification',
      '5+ years in tax advisory or compliance',
      'Strong knowledge of current tax legislation',
      'Excellent analytical and client-management skills',
    ],
    benefits: ['Competitive salary', 'Health & dental insurance', 'Pension', 'Professional development', 'Performance bonus'],
    skills: ['Taxation', 'Tax Planning', 'Compliance', 'Advisory', 'Tax Law'],
    deadline: '2026-07-25',
    postedAt: '2026-06-14',
    applications: 35,
    isActive: true,
    isFeatured: false,
    status: 'approved',
  },
  {
    _id: 'j005',
    title: 'Investment / Capital Markets Analyst Intern',
    company: 'Sterling Securities Ltd',
    companyLogo: null,
    location: 'Remote',
    locationType: 'Remote',
    type: 'Internship',
    category: 'Finance',
    salary: { min: 150000, max: 220000, currency: 'NGN', period: 'monthly' },
    experience: '0-1 year',
    level: 'Entry',
    description:
      'Support the capital markets desk with research, financial modelling and transaction preparation at a leading securities firm.',
    responsibilities: ['Build financial models', 'Prepare research and pitch materials', 'Support live transactions'],
    requirements: ['Finance, Economics or related degree', 'Strong Excel and analytical skills'],
    benefits: ['Mentorship', 'Certificate', 'Flexible schedule'],
    skills: ['Financial Modelling', 'Capital Markets', 'Research', 'Excel', 'Valuation'],
    deadline: '2026-07-22',
    postedAt: '2026-06-09',
    applications: 64,
    isActive: true,
    isFeatured: true,
    status: 'approved',
  },
];
